#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys
import uuid
from typing import Dict, Optional, List


DEFAULT_TENANT = "00000000-0000-0000-0000-000000000000"

DB_SERVICE = "postgres"
DB_USER = "postgres"
DB_NAME = "lotus_warden"

SOURCE_TYPE = "stress-seed"
SOURCE_VERSION = "v1"

DEFAULT_SCANNER = "semgrep"
DEFAULT_PRODUCT_IDENTIFIER = "stress-seed"
DEFAULT_PRODUCT_NAME = "Stress Seed"


def run(
    cmd: List[str], *, input_text: Optional[str] = None, check: bool = True
) -> subprocess.CompletedProcess:
    p = subprocess.run(
        cmd,
        input=(input_text.encode("utf-8") if input_text is not None else None),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and p.returncode != 0:
        out = p.stdout.decode("utf-8", "ignore")
        err = p.stderr.decode("utf-8", "ignore")
        raise RuntimeError(
            f"Command failed: {' '.join(cmd)}\nSTDOUT:\n{out}\nSTDERR:\n{err}"
        )
    return p


def detect_compose_cmd() -> List[str]:
    # Prefer: docker compose ...
    try:
        run(["docker", "compose", "version"], check=True)
        return ["docker", "compose"]
    except Exception:
        pass

    # Fallback: docker-compose ...
    try:
        run(["docker-compose", "version"], check=True)
        return ["docker-compose"]
    except Exception:
        raise RuntimeError("Не найден docker compose / docker-compose в PATH.")


def ensure_postgres_running(compose_cmd: List[str]) -> None:
    p = run(compose_cmd + ["ps", "-q", DB_SERVICE], check=False)
    cid = p.stdout.decode("utf-8", "ignore").strip()
    if not cid:
        print("[i] Postgres не запущен — запускаю `docker compose up -d postgres` ...")
        run(compose_cmd + ["up", "-d", DB_SERVICE], check=True)


def psql(
    compose_cmd: List[str], sql: str, *, vars: Optional[Dict[str, str]] = None
) -> str:
    """
    Executes SQL via psql inside postgres container, returns ONLY the first non-empty output line.
    -X : ignore ~/.psqlrc
    -q : quiet
    -A -t : unaligned + tuples-only
    """
    cmd = compose_cmd + [
        "exec",
        "-T",
        DB_SERVICE,
        "psql",
        "-X",
        "-q",
        "-U",
        DB_USER,
        "-d",
        DB_NAME,
        "-v",
        "ON_ERROR_STOP=1",
        "-At",
    ]
    if vars:
        for k, v in vars.items():
            cmd += ["-v", f"{k}={v}"]

    p = run(cmd, input_text=sql, check=True)
    out = p.stdout.decode("utf-8", "ignore") if p.stdout else ""
    lines = [line.strip() for line in out.splitlines() if line.strip()]
    return lines[0] if lines else ""


def must_uuid(value: str, name: str) -> str:
    try:
        uuid.UUID(value)
        return value
    except Exception:
        raise RuntimeError(f"{name} не похож на UUID: {value}")


def ensure_extensions(compose_cmd: List[str]) -> None:
    psql(compose_cmd, "CREATE EXTENSION IF NOT EXISTS pgcrypto;")


def resolve_tenant_id(compose_cmd: List[str], arg_tenant_id: Optional[str]) -> str:
    if arg_tenant_id:
        return must_uuid(arg_tenant_id, "tenant_id")

    # Prefer root@localhost user tenant if exists, else default.
    tid = psql(
        compose_cmd,
        "SELECT tenant_id::text FROM users WHERE email='root@localhost' LIMIT 1;",
    ).strip()
    if tid:
        return must_uuid(tid, "tenant_id(from users.root@localhost)")
    return DEFAULT_TENANT


def resolve_or_create_product(
    compose_cmd: List[str], tenant_id: str, product_id: Optional[str]
) -> str:
    if product_id:
        return must_uuid(product_id, "product_id")

    # Find by tenant+identifier first
    existing = psql(
        compose_cmd,
        "SELECT id::text FROM products WHERE tenant_id = :'tenant'::uuid AND identifier = :'ident' LIMIT 1;",
        vars={"tenant": tenant_id, "ident": DEFAULT_PRODUCT_IDENTIFIER},
    ).strip()
    if existing:
        return must_uuid(existing, "product_id(found)")

    # Create new
    for _ in range(10):
        slug_suffix = uuid.uuid4().hex[:8]
        new_id = psql(
            compose_cmd,
            """
            INSERT INTO products (tenant_id, name, slug, identifier, description)
            VALUES (:'tenant'::uuid, :'name', :'slug', :'ident', 'Generated by stress_seed_findings.py')
            RETURNING id::text;
            """,
            vars={
                "tenant": tenant_id,
                "name": DEFAULT_PRODUCT_NAME,
                "slug": f"stress-seed-{slug_suffix}",
                "ident": DEFAULT_PRODUCT_IDENTIFIER,
            },
        ).strip()
        if new_id:
            return must_uuid(new_id, "product_id(created)")

    raise RuntimeError("Не удалось создать product (slug/identifier конфликтуют?)")


def create_scan_result(
    compose_cmd: List[str], tenant_id: str, product_id: str, scanner: str
) -> str:
    scan_id = psql(
        compose_cmd,
        """
        INSERT INTO scan_results (tenant_id, product_id, scanner, source_type, source_version, processed_at)
        VALUES (:'tenant'::uuid, :'product'::uuid, :'scanner', :'source_type', :'source_version', now())
        RETURNING id::text;
        """,
        vars={
            "tenant": tenant_id,
            "product": product_id,
            "scanner": scanner,
            "source_type": SOURCE_TYPE,
            "source_version": SOURCE_VERSION,
        },
    ).strip()
    return must_uuid(scan_id, "scan_result_id")


def cleanup_seed(
    compose_cmd: List[str], tenant_id: str, product_id: str, scanner: str
) -> None:
    deleted_scans = psql(
        compose_cmd,
        """
        WITH d AS (
          DELETE FROM scan_results
          WHERE tenant_id = :'tenant'::uuid
            AND product_id = :'product'::uuid
            AND scanner = :'scanner'
            AND source_type = :'source_type'
            AND source_version = :'source_version'
          RETURNING 1
        )
        SELECT COALESCE(COUNT(*),0)::text FROM d;
        """,
        vars={
            "tenant": tenant_id,
            "product": product_id,
            "scanner": scanner,
            "source_type": SOURCE_TYPE,
            "source_version": SOURCE_VERSION,
        },
    ).strip()
    print(
        f"[ok] cleanup: удалено scan_results={deleted_scans} (findings удалятся каскадом)"
    )


def seed_semgrep_findings(
    compose_cmd: List[str],
    tenant_id: str,
    product_id: str,
    scan_result_id: str,
    count: int,
    chunk: int,
    seed: str,
) -> None:
    if chunk <= 0:
        chunk = count

    # IMPORTANT: We are inside a python f-string later, so we must escape '{' and '}' in any literals we want
    # to keep (GitHub Actions expressions, etc.)
    gh_expr = "${{{{ inputs.box_ticked }}}}"  # -> "${{ inputs.box_ticked }}"
    shell_var = "${{BOX_TICKED}}"  # -> "${BOX_TICKED}"
    code_line = f'      - run: echo "was the box ticked? {shell_var}! ({gh_expr})"'

    # Message contains `${{...}}` inside backticks – must be escaped for f-string too.
    msg = (
        "Using variable interpolation `${{{{...}}}}` with `github` context data in a `run:` step could allow an "
        "attacker to inject their own code into the runner. This would allow them to steal secrets and code. "
        "`github` context data can have arbitrary user input and should be treated as untrusted. Instead, use an "
        "intermediate environment variable with `env:` to store the data and use the environment variable in the "
        '`run:` script. Be sure to use double-quotes the environment variable, like this: "$ENVVAR".'
    )

    inserted_total = 0
    start = 1
    while start <= count:
        end = min(count, start + chunk - 1)
        this_n = end - start + 1
        print(f"[i] inserting findings {start}..{end} ({this_n}) ...")

        sql = f"""
        BEGIN;
        SET LOCAL synchronous_commit TO off;

        INSERT INTO findings (
          tenant_id,
          product_id,
          scan_result_id,
          fingerprint,
          title,
          description,
          severity,
          status,
          category,
          source_type,
          source_version,
          evidence,
          raw_data,
          first_seen_at,
          last_seen_at,
          created_at,
          updated_at
        )
        SELECT
          :'tenant'::uuid,
          :'product'::uuid,
          :'scan_result'::uuid,

          encode(digest(
            ('semgrep|' || :'seed' || '|' ||
             'yaml.github-actions.security.run-shell-injection.run-shell-injection' || '|' ||
             format('.github/workflows/workflow_%s.yml', (i % 500) + 1) || '|' ||
             ((i % 200) + 1)::text || '|' || i::text),
            'sha256'
          ), 'hex'),

          format('Run shell injection: workflow_%s.yml:%s', (i % 500) + 1, (i % 200) + 1),

          'Stress-seeded Semgrep finding',

          'high',
          'new',
          'SAST',
          :'source_type',
          :'source_version',

          jsonb_build_object(
            'scannerType','semgrep',
            'ruleId','yaml.github-actions.security.run-shell-injection.run-shell-injection',
            'path', format('.github/workflows/workflow_%s.yml', (i % 500) + 1),
            'start', jsonb_build_object('line', (i % 200) + 1, 'col', 9),
            'end',   jsonb_build_object('line', (i % 200) + 1, 'col', 82),
            'message', {sql_quote(msg)},
            'severityRaw','ERROR',
            'code', {sql_quote(code_line)},
            'metadata', jsonb_build_object(
              'category','security',
              'technology', jsonb_build_array('github-actions'),
              'references', jsonb_build_array(
                'https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections',
                'https://securitylab.github.com/research/github-actions-untrusted-input/'
              ),
              'vulnerability_class', jsonb_build_array('Command Injection'),
              'likelihood','HIGH','impact','HIGH','confidence','HIGH'
            ),
            'cwe',   jsonb_build_array('CWE-78'),
            'owasp', jsonb_build_array('A01:2017 - Injection','A03:2021 - Injection')
          ),

          jsonb_build_object(
            'check_id', 'yaml.github-actions.security.run-shell-injection.run-shell-injection',
            'path', format('.github/workflows/workflow_%s.yml', (i % 500) + 1),
            'start', jsonb_build_object('line', (i % 200) + 1, 'col', 9, 'offset', 300 + (i % 1000)),
            'end',   jsonb_build_object('line', (i % 200) + 1, 'col', 82, 'offset', 373 + (i % 1000)),
            'extra', jsonb_build_object(
              'message', {sql_quote(msg)},
              'severity', 'ERROR',
              'lines', {sql_quote(code_line)},
              'is_ignored', false,
              'validation_state', 'NO_VALIDATOR',
              'engine_kind', 'PRO',
              'metavars', jsonb_build_object(
                '$SHELL', jsonb_build_object(
                  'start', jsonb_build_object('line', (i % 200) + 1, 'col', 14, 'offset', 305 + (i % 1000)),
                  'end',   jsonb_build_object('line', (i % 200) + 1, 'col', 82, 'offset', 373 + (i % 1000)),
                  'abstract_content', {sql_quote(code_line)}
                )
              ),
              'metadata', jsonb_build_object(
                'category', 'security',
                'cwe', jsonb_build_array('CWE-78: Improper Neutralization of Special Elements used in an OS Command (OS Command Injection)'),
                'owasp', jsonb_build_array('A01:2017 - Injection','A03:2021 - Injection'),
                'references', jsonb_build_array(
                  'https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections',
                  'https://securitylab.github.com/research/github-actions-untrusted-input/'
                ),
                'technology', jsonb_build_array('github-actions'),
                'likelihood', 'HIGH',
                'impact', 'HIGH',
                'confidence', 'HIGH'
              )
            )
          ),

          now() - ((i % 720)::text || ' minutes')::interval,
          now() - ((i % 60)::text  || ' minutes')::interval,
          now() - ((i % 720)::text || ' minutes')::interval,
          now() - ((i % 60)::text  || ' minutes')::interval

        FROM generate_series({start}, {end}) AS i;

        COMMIT;
        """

        psql(
            compose_cmd,
            sql,
            vars={
                "tenant": tenant_id,
                "product": product_id,
                "scan_result": scan_result_id,
                "seed": seed,
                "source_type": SOURCE_TYPE,
                "source_version": SOURCE_VERSION,
            },
        )

        inserted_total += this_n
        start = end + 1

    print(f"[ok] inserted total: {inserted_total}")


def sql_quote(s: str) -> str:
    # safe enough for our controlled strings: single quotes doubled
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Seed Lotus-Warden Postgres with Semgrep-like findings (evidence+raw_data)."
    )
    ap.add_argument(
        "--count",
        type=int,
        default=100_000,
        help="Сколько findings добавить (default: 100000)",
    )
    ap.add_argument(
        "--chunk", type=int, default=20_000, help="Размер чанка (default: 20000)"
    )
    ap.add_argument(
        "--tenant-id",
        default=os.getenv("TENANT_ID"),
        help="Tenant UUID (если не задан — root@localhost или default)",
    )
    ap.add_argument(
        "--product-id",
        default=os.getenv("PRODUCT_ID"),
        help="Product UUID (если не задан — создадим/найдем stress-seed)",
    )
    ap.add_argument(
        "--scanner",
        default=DEFAULT_SCANNER,
        help="scanner для scan_results (default: semgrep)",
    )
    ap.add_argument(
        "--cleanup",
        action="store_true",
        help="Удалить ранее созданные stress-seed scan_results (+ findings каскадом) и выйти",
    )
    args = ap.parse_args()

    if args.count <= 0 and not args.cleanup:
        raise RuntimeError("--count должен быть > 0")

    compose_cmd = detect_compose_cmd()
    ensure_postgres_running(compose_cmd)
    ensure_extensions(compose_cmd)

    tenant_id = resolve_tenant_id(compose_cmd, args.tenant_id)
    product_id = resolve_or_create_product(compose_cmd, tenant_id, args.product_id)

    print(f"[i] tenant_id={tenant_id}")
    print(f"[i] product_id={product_id}")
    print(f"[i] scanner={args.scanner}")

    if args.cleanup:
        cleanup_seed(compose_cmd, tenant_id, product_id, args.scanner)
        return

    scan_result_id = create_scan_result(
        compose_cmd, tenant_id, product_id, args.scanner
    )
    print(f"[i] scan_result_id={scan_result_id}")

    seed = uuid.uuid4().hex
    print(f"[i] seeding {args.count} findings (seed={seed}) ...")

    seed_semgrep_findings(
        compose_cmd=compose_cmd,
        tenant_id=tenant_id,
        product_id=product_id,
        scan_result_id=scan_result_id,
        count=args.count,
        chunk=args.chunk,
        seed=seed,
    )

    psql(compose_cmd, "ANALYZE findings;")
    psql(compose_cmd, "ANALYZE scan_results;")

    total = psql(
        compose_cmd,
        """
        SELECT COUNT(*)::text
        FROM findings
        WHERE tenant_id = :'tenant'::uuid
          AND product_id = :'product'::uuid
          AND (duplicate_id IS NULL OR duplicate_id IS NULL) -- tolerate schema variance
          AND (deleted_at IS NULL OR deleted_at IS NULL);
        """,
        vars={"tenant": tenant_id, "product": product_id},
    ).strip()

    print(f"[ok] total findings in product now (rough): {total}")
    print(
        f"[i] cleanup: python stress_seed_findings.py --cleanup --scanner {args.scanner}"
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[ERR] {e}", file=sys.stderr)
        sys.exit(1)
