[uwsgi]
module = lotus_warden.wsgi:application
master = true
processes = 2
threads = 4
socket = /run/uwsgi/lotus_warden.sock
chmod-socket = 660
vacuum = true
enable-threads = true
harakiri = 30
max-requests = 1000
log-format = %(addr) - %(method) %(uri) => %(status) in %(msecs)ms
