server {
    listen 8080;

    location = /healthz {
        access_log off;
        return 204;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 8443 ssl http2;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/redlycoris/tls/fullchain.crt;
    ssl_certificate_key /etc/redlycoris/tls/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:TLS:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    include /etc/redlycoris/tls/tls-mode.conf;

    resolver 127.0.0.11 ipv6=off;
    set $backend_upstream backend:8080;

    location /api/ {
        proxy_pass http://$backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
