# Generated by Django 6.0.1 on 2026-01-14 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('risk_accepted', 'Risk Accepted')], default='new', max_length=20)),
                ('vuln_id', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('component', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=1000)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('repo', 'Repository'), ('image', 'Container Image'), ('host', 'Host'), ('url', 'URL')], max_length=20)),
                ('identifier', models.CharField(max_length=500)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('criticality', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_version', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('raw_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('raw_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.asset')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.finding')),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.scanrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'status', 'severity'], name='core_findin_project_c3cc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'last_seen'], name='core_findin_project_88b234_idx'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='uniq_finding_per_project_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('project', 'asset_type', 'identifier'), name='uniq_asset_per_project'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['project', 'status', 'created_at'], name='core_scanru_project_e812d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.UniqueConstraint(fields=('project', 'tool_name', 'idempotency_key'), name='uniq_scanrun_idempotency'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['finding', 'observed_at'], name='core_occurr_finding_4c83fa_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['scan_run'], name='core_occurr_scan_ru_b16281_idx'),
        ),
    ]
